package com.huemux.app

import android.content.ContentValues
import android.content.Context
import android.media.MediaCodec
import android.media.MediaCodecInfo
import android.media.MediaFormat
import android.media.MediaMuxer
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.os.ParcelFileDescriptor
import android.provider.MediaStore
import android.util.Log
import com.huemux.mobile.Mobile
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Records the screen by encoding the frames screen sync is already capturing.
 *
 * ## Why this exists alongside [ScreenRecorder]
 *
 * The first recorder asked MediaProjection for a second VirtualDisplay and
 * pointed a MediaRecorder at it. On the device this was written for, that
 * failed — and left no trace anywhere, because the whole media stack lives in
 * Kotlin and the diagnostics report is generated by Go. (Both problems are
 * fixed: everything here reports through [Mobile.LogHost].)
 *
 * This path needs no second mirror at all. The capture pipeline already
 * receives every frame as tightly-packed RGB on its way to the colour engine;
 * that same buffer is converted to YUV and pushed into an H.264 encoder. One
 * projection, one virtual display, one stream feeding two consumers — which is
 * what the second display was only ever an awkward way of achieving.
 *
 * The trade is resolution: this records exactly what the pipeline captures, so
 * a recording is as sharp as the capture-resolution setting makes it. That is
 * the right default (it cannot fail for want of a second display, and it shows
 * what the sync engine actually reacted to). [ScreenRecorder] remains for the
 * full-resolution case, where a separate mirror is genuinely necessary.
 *
 * ## Cost
 *
 * Colour conversion and encoding happen on the capture thread, inline with the
 * frame. At the default capture size that is ~110k pixels a frame and costs a
 * couple of milliseconds; at a raised capture resolution it is proportionally
 * more, and it will show up as reduced capture throughput rather than as
 * dropped video. Encoding never blocks: if the encoder has no input buffer
 * free the frame is skipped, because the light pipeline must not stall behind
 * the recorder.
 */
class FrameRecorder(private val ctx: Context) {

    @Volatile
    var isRecording: Boolean = false
        private set

    @Volatile
    var lastOutput: String = ""
        private set

    private var codec: MediaCodec? = null
    private var muxer: MediaMuxer? = null
    private var trackIndex = -1
    private var muxerStarted = false

    private var pfd: ParcelFileDescriptor? = null
    private var uri: Uri? = null
    private var file: File? = null
    private var name = ""

    private var encW = 0
    private var encH = 0
    private var colorFormat = 0
    private var yuv: ByteArray? = null
    private var startNs = 0L
    private var framesIn = 0
    private var framesOut = 0
    private var lastError = ""

    /** Frames accepted by the encoder, for the diagnostics block. */
    fun stats(): String =
        "${encW}x$encH in=$framesIn out=$framesOut" + if (lastError.isNotEmpty()) " err=$lastError" else ""

    /**
     * Prepares the encoder for a capture of [srcW] x [srcH]. Returns null on
     * success or a message for the UI; never throws.
     */
    @Synchronized
    fun start(srcW: Int, srcH: Int): String? {
        if (isRecording) return "already recording"
        lastError = ""

        // Encoders reject odd sizes, and reject non-multiples of 16 often
        // enough that it is not worth discovering per-device. Crop rather than
        // scale: dropping up to 15 columns costs nothing visible and keeps the
        // conversion a straight copy with no resampling.
        encW = (srcW / 16) * 16
        encH = (srcH / 16) * 16
        if (encW < 64 || encH < 64) {
            return "capture is too small to record (${srcW}x$srcH)"
        }

        val fmt = MediaFormat.createVideoFormat(MIME, encW, encH)
        colorFormat = pickColorFormat()
        if (colorFormat == 0) {
            Mobile.logHost("record: no usable encoder colour format for $MIME")
            return "no compatible video encoder on this device"
        }
        fmt.setInteger(MediaFormat.KEY_COLOR_FORMAT, colorFormat)
        fmt.setInteger(MediaFormat.KEY_BIT_RATE, bitrateFor(encW, encH))
        fmt.setInteger(MediaFormat.KEY_FRAME_RATE, FRAME_RATE)
        fmt.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 2)

        try {
            openOutput()
        } catch (e: Exception) {
            Mobile.logHost("record: output file failed: ${e.message}")
            Log.e(TAG, "output file", e)
            cleanup()
            return "could not create the video file: " + (e.message ?: e.toString())
        }

        try {
            val c = MediaCodec.createEncoderByType(MIME)
            c.configure(fmt, null, null, MediaCodec.CONFIGURE_FLAG_ENCODE)
            c.start()
            codec = c
        } catch (e: Exception) {
            Mobile.logHost("record: encoder configure failed ${encW}x$encH fmt=$colorFormat: ${e.message}")
            Log.e(TAG, "encoder configure", e)
            cleanup()
            return "this device would not encode ${encW}x$encH: " + (e.message ?: e.toString())
        }

        try {
            val out = pfd
            muxer = if (out != null) {
                MediaMuxer(out.fileDescriptor, MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4)
            } else {
                MediaMuxer(file!!.absolutePath, MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4)
            }
        } catch (e: Exception) {
            Mobile.logHost("record: muxer failed: ${e.message}")
            Log.e(TAG, "muxer", e)
            cleanup()
            return "could not start the video writer: " + (e.message ?: e.toString())
        }

        yuv = ByteArray(encW * encH * 3 / 2)
        startNs = System.nanoTime()
        framesIn = 0
        framesOut = 0
        isRecording = true
        Mobile.logHost("record: started ${encW}x$encH fmt=$colorFormat -> $name")
        return null
    }

    /**
     * Encodes one captured frame. [rgb] is tightly packed RGB of [srcW] x
     * [srcH] — the same buffer being handed to the colour engine, which is why
     * this must not retain it.
     *
     * Every failure here is swallowed after being logged once: a recorder that
     * throws into the capture path would take screen sync down with it, and
     * sync is the thing worth protecting.
     */
    @Synchronized
    fun onFrame(rgb: ByteArray, srcW: Int, srcH: Int) {
        val c = codec ?: return
        if (!isRecording) return
        // A capture-size change while recording would silently corrupt every
        // subsequent frame, since the conversion below trusts these.
        if (srcW < encW || srcH < encH) return

        try {
            val index = c.dequeueInputBuffer(0)
            if (index < 0) {
                // No free input buffer. Dropping this frame is correct: the
                // alternative is blocking the capture thread, which delays the
                // lights for the benefit of the recording.
                drain(false)
                return
            }
            val buf = c.getInputBuffer(index) ?: return
            val dst = yuv ?: return
            rgbToYuv(rgb, srcW, dst)
            buf.clear()
            buf.put(dst, 0, dst.size)
            val ptsUs = (System.nanoTime() - startNs) / 1000
            c.queueInputBuffer(index, 0, dst.size, ptsUs, 0)
            framesIn++
            drain(false)
        } catch (e: Exception) {
            if (lastError.isEmpty()) {
                lastError = e.message ?: e.toString()
                Mobile.logHost("record: frame failed: $lastError")
                Log.w(TAG, "frame encode", e)
            }
        }
    }

    /** Finalises the file. Returns null on success or a message. */
    @Synchronized
    fun stop(): String? {
        if (!isRecording) return null
        isRecording = false
        var err: String? = null

        try {
            val c = codec
            if (c != null) {
                val index = c.dequeueInputBuffer(10000)
                if (index >= 0) {
                    c.queueInputBuffer(index, 0, 0, (System.nanoTime() - startNs) / 1000,
                        MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                }
                drain(true)
            }
        } catch (e: Exception) {
            Log.w(TAG, "draining encoder", e)
        }

        if (framesOut == 0) {
            // No frames reached the muxer, so the file is an unplayable stub.
            // Say so rather than leaving a 0-byte MP4 in the gallery.
            err = "the recording was too short to save"
        }

        try {
            codec?.stop()
        } catch (e: Exception) {
            Log.w(TAG, "codec stop", e)
        }
        try {
            codec?.release()
        } catch (e: Exception) {
            Log.w(TAG, "codec release", e)
        }
        codec = null

        try {
            if (muxerStarted) muxer?.stop()
        } catch (e: Exception) {
            Log.w(TAG, "muxer stop", e)
            if (err == null) err = "the video file could not be finalised"
        }
        try {
            muxer?.release()
        } catch (e: Exception) {
            Log.w(TAG, "muxer release", e)
        }
        muxer = null
        muxerStarted = false
        trackIndex = -1

        Mobile.logHost("record: stopped in=$framesIn out=$framesOut err=${err ?: "none"}")
        publishOutput(err == null)
        lastOutput = if (err == null) name else ""
        yuv = null
        return err
    }

    // --- encoder plumbing --------------------------------------------------

    private fun drain(endOfStream: Boolean) {
        val c = codec ?: return
        val info = MediaCodec.BufferInfo()
        while (true) {
            val index = c.dequeueOutputBuffer(info, if (endOfStream) 10000 else 0)
            if (index == MediaCodec.INFO_TRY_AGAIN_LATER) {
                if (!endOfStream) return
                // Waiting for the end-of-stream flag; a codec that never sends
                // it would hang here, so bail after the timeout above rather
                // than loop forever.
                return
            }
            if (index == MediaCodec.INFO_OUTPUT_FORMAT_CHANGED) {
                // The only point at which the muxer can learn the real format:
                // adding the track before this fires produces a file with no
                // codec-specific data, which nothing will play.
                val m = muxer ?: return
                trackIndex = m.addTrack(c.outputFormat)
                m.start()
                muxerStarted = true
                continue
            }
            if (index < 0) continue

            val buf = c.getOutputBuffer(index)
            if (buf != null && info.size > 0 && muxerStarted &&
                (info.flags and MediaCodec.BUFFER_FLAG_CODEC_CONFIG) == 0
            ) {
                buf.position(info.offset)
                buf.limit(info.offset + info.size)
                muxer?.writeSampleData(trackIndex, buf, info)
                framesOut++
            }
            c.releaseOutputBuffer(index, false)
            if ((info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM) != 0) return
        }
    }

    /**
     * Converts tightly-packed RGB to the encoder's chosen YUV layout, cropping
     * to [encW] x [encH] from the top-left. [srcStrideW] is the source frame's
     * width, which may be wider than the crop.
     *
     * Chroma is sampled from the top-left pixel of each 2x2 block rather than
     * averaged. Averaging is four times the work for a difference that is
     * invisible on screen content, which is flat colour and hard edges.
     */
    private fun rgbToYuv(rgb: ByteArray, srcStrideW: Int, out: ByteArray) {
        val planar = colorFormat == MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Planar
        val frameSize = encW * encH
        val chromaSize = frameSize / 4
        var yi = 0
        for (row in 0 until encH) {
            var si = row * srcStrideW * 3
            for (col in 0 until encW) {
                val r = rgb[si].toInt() and 0xff
                val g = rgb[si + 1].toInt() and 0xff
                val b = rgb[si + 2].toInt() and 0xff
                si += 3
                out[yi++] = (((66 * r + 129 * g + 25 * b + 128) shr 8) + 16).toByte()
                if ((row and 1) == 0 && (col and 1) == 0) {
                    val u = ((-38 * r - 74 * g + 112 * b + 128) shr 8) + 128
                    val v = ((112 * r - 94 * g - 18 * b + 128) shr 8) + 128
                    val ci = (row / 2) * (encW / 2) + (col / 2)
                    if (planar) {
                        out[frameSize + ci] = clamp(u)
                        out[frameSize + chromaSize + ci] = clamp(v)
                    } else {
                        // Semi-planar (NV12): U and V interleaved, U first.
                        out[frameSize + ci * 2] = clamp(u)
                        out[frameSize + ci * 2 + 1] = clamp(v)
                    }
                }
            }
        }
    }

    private fun clamp(v: Int): Byte = when {
        v < 0 -> 0
        v > 255 -> 255.toByte()
        else -> v.toByte()
    }

    /**
     * Picks a colour format the device's H.264 encoder actually advertises.
     * Assuming NV12 is the single most common way a hand-rolled encoder path
     * works on the author's phone and produces green-and-magenta garbage on
     * someone else's.
     */
    private fun pickColorFormat(): Int {
        try {
            val codec = MediaCodec.createEncoderByType(MIME)
            val caps = codec.codecInfo.getCapabilitiesForType(MIME)
            codec.release()
            val available = caps.colorFormats.toSet()
            for (want in intArrayOf(
                MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420SemiPlanar,
                MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Planar,
            )) {
                if (available.contains(want)) return want
            }
            Mobile.logHost("record: encoder offers only ${available.joinToString(",")}")
        } catch (e: Exception) {
            Mobile.logHost("record: could not query encoder: ${e.message}")
            Log.e(TAG, "query encoder", e)
        }
        return 0
    }

    // --- output plumbing ---------------------------------------------------
    // Same two paths as ScreenRecorder, and for the same reasons: MediaStore
    // from Android 10, where shared storage cannot be written by path, and an
    // app-scoped file below that, where the alternative is asking for
    // WRITE_EXTERNAL_STORAGE to save a convenience video.

    private fun openOutput() {
        name = "huemux-" + SimpleDateFormat("yyyyMMdd-HHmmss", Locale.US).format(Date()) + ".mp4"
        if (Build.VERSION.SDK_INT >= 29) {
            val values = ContentValues().apply {
                put(MediaStore.Video.Media.DISPLAY_NAME, name)
                put(MediaStore.Video.Media.MIME_TYPE, "video/mp4")
                put(MediaStore.Video.Media.RELATIVE_PATH, Environment.DIRECTORY_MOVIES + "/HueMux")
                put(MediaStore.Video.Media.IS_PENDING, 1)
            }
            val u = ctx.contentResolver.insert(MediaStore.Video.Media.EXTERNAL_CONTENT_URI, values)
                ?: throw IllegalStateException("MediaStore refused the entry")
            uri = u
            pfd = ctx.contentResolver.openFileDescriptor(u, "w")
                ?: throw IllegalStateException("MediaStore gave no file descriptor")
            return
        }
        val dir = ctx.getExternalFilesDir(Environment.DIRECTORY_MOVIES)
            ?: throw IllegalStateException("no external files directory")
        dir.mkdirs()
        file = File(dir, name)
    }

    private fun publishOutput(ok: Boolean) {
        try {
            pfd?.close()
        } catch (e: Exception) {
            Log.w(TAG, "closing descriptor", e)
        }
        pfd = null

        val u = uri
        if (u != null) {
            try {
                if (ok) {
                    ctx.contentResolver.update(
                        u, ContentValues().apply { put(MediaStore.Video.Media.IS_PENDING, 0) },
                        null, null,
                    )
                } else {
                    // A pending entry nobody clears keeps its bytes and stays
                    // invisible in the gallery forever.
                    ctx.contentResolver.delete(u, null, null)
                }
            } catch (e: Exception) {
                Log.w(TAG, "publishing entry", e)
            }
        } else if (!ok) {
            file?.delete()
        }
        uri = null
        file = null
    }

    private fun cleanup() {
        try {
            codec?.release()
        } catch (e: Exception) {
            Log.w(TAG, "cleanup codec", e)
        }
        codec = null
        try {
            muxer?.release()
        } catch (e: Exception) {
            Log.w(TAG, "cleanup muxer", e)
        }
        muxer = null
        muxerStarted = false
        publishOutput(false)
        isRecording = false
    }

    private companion object {
        const val TAG = "HueMuxFrameRec"
        const val MIME = "video/avc"
        const val FRAME_RATE = 30

        fun bitrateFor(w: Int, h: Int): Int =
            (w.toLong() * h.toLong() * FRAME_RATE / 10).toInt().coerceIn(500_000, 20_000_000)
    }
}
