#!/usr/bin/env bash
# Regenerate web/THIRD_PARTY_LICENSES.md from the modules actually linked into
# the shipped binaries.
#
# Not go-licenses: it reports every stdlib package as an error on a modern
# toolchain (google/go-licenses#128) and produced nothing usable here. This
# reads `go list -deps`, which is the same set the linker sees, and copies each
# module's licence text verbatim out of the module cache — so the file cannot
# drift from what is actually distributed, and cannot claim a licence the
# module does not ship.
#
# CI runs this and fails if the result differs from what is committed, which is
# what stops a new dependency being added without its attribution.
#
#   scripts/gen-third-party-licenses.sh          # write the file
#   scripts/gen-third-party-licenses.sh --check  # exit 1 if it would change

set -euo pipefail
cd "$(dirname "$0")/.."

OUT=web/THIRD_PARTY_LICENSES.md
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

# Licences we accept. GPL-3.0-or-later (this project) can absorb all of these.
# Anything not listed stops the build rather than being silently bundled —
# a copyleft dependency arriving unnoticed is exactly what this guards.
ALLOWED_RE='^(MIT|BSD-2-Clause|BSD-3-Clause|Apache-2.0|ISC)$'

modules=$(go list -deps -f '{{if .Module}}{{.Module.Path}} {{.Module.Version}}{{end}}' \
  ./cmd/huemux ./cmd/huemux-desktop ./mobile 2>/dev/null \
  | sort -u | grep -v '^github.com/zamber/huemux' | grep -v '^$')

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

cat >> "$tmp" <<'HEADER'
# Third-party licences

HueMux is GPL-3.0-or-later (see [LICENSE](../LICENSE)). It bundles the
components below, each under its own licence, reproduced here in full as those
licences require.

This file is generated by `scripts/gen-third-party-licenses.sh` from the
modules the linker actually pulls in, and CI fails if it is out of date. Do not
edit it by hand.

HEADER

# --- contents ---------------------------------------------------------------
{
  echo "## Contents"
  echo
  echo "- [Fira Code](#fira-code) — SIL OFL 1.1"
  while read -r mod ver; do
    [ -z "$mod" ] && continue
    anchor=$(echo "$mod" | tr '[:upper:]/.' '[:lower:]--')
    echo "- [$mod](#$anchor) — $ver"
  done <<< "$modules"
  echo
  echo "The Electron desktop build additionally downloads Electron at first"
  echo "run (MIT, over Chromium's BSD-3-Clause and an LGPL-2.1 ffmpeg); its"
  echo "licences ship inside that download rather than here, since it is not"
  echo "redistributed by this project."
  echo
} >> "$tmp"

# --- the bundled font -------------------------------------------------------
{
  echo "---"
  echo
  echo "## Fira Code"
  echo
  echo "Bundled at \`web/shared/fonts/\`. Reserved font name: a modified version"
  echo "may not be called Fira Code. The font may not be sold on its own."
  echo
  echo '```'
  cat web/shared/fonts/LICENSE-OFL.txt
  echo '```'
  echo
} >> "$tmp"

# --- each Go module ---------------------------------------------------------
while read -r mod ver; do
  [ -z "$mod" ] && continue
  dir="$(go env GOMODCACHE)/$(echo "$mod" | sed 's/\([A-Z]\)/!\l\1/g')@$ver"
  lic=$(find "$dir" -maxdepth 1 \( -iname 'LICENSE*' -o -iname 'COPYING*' \) -type f 2>/dev/null | head -1)
  if [ -z "$lic" ]; then
    echo "ERROR: no licence file found for $mod $ver in $dir" >&2
    exit 1
  fi

  # Identify the licence from its own text, so the label cannot disagree with
  # the thing it labels.
  if   grep -qi 'Apache License' "$lic";                     then id=Apache-2.0
  elif grep -qi 'Redistributions of source code' "$lic" \
    && grep -qi 'Neither the name' "$lic";                   then id=BSD-3-Clause
  elif grep -qi 'Redistributions of source code' "$lic";      then id=BSD-2-Clause
  elif grep -qi 'Permission is hereby granted, free of charge' "$lic"; then id=MIT
  elif grep -qi 'Permission to use, copy, modify, and.*distribute' "$lic"; then id=ISC
  else id=UNKNOWN
  fi

  if ! echo "$id" | grep -qE "$ALLOWED_RE"; then
    echo "ERROR: $mod $ver has licence '$id', which is not in the allowlist." >&2
    echo "       Check it is compatible with GPL-3.0-or-later before adding it." >&2
    exit 1
  fi

  {
    echo "---"
    echo
    echo "## $mod"
    echo
    echo "Version $ver — $id"
    echo
    echo '```'
    cat "$lic"
    echo '```'
    echo
  } >> "$tmp"
done <<< "$modules"

if [ "$CHECK" = 1 ]; then
  if ! diff -q "$tmp" "$OUT" >/dev/null 2>&1; then
    echo "ERROR: $OUT is out of date. Run scripts/gen-third-party-licenses.sh" >&2
    diff -u "$OUT" "$tmp" | head -40 >&2 || true
    exit 1
  fi
  echo "$OUT is up to date"
else
  cp "$tmp" "$OUT"
  echo "wrote $OUT ($(wc -l < "$OUT") lines, $(echo "$modules" | grep -c . ) modules)"
fi
